/**
 * 前后端共享的 API 错误码与图标来源码
 *
 * Worker 只返回语言无关的标识（响应体的 error / source 字段），
 * 前端通过 translateApiError / translateIconSource 查询对应语言的文案展示，
 * 这样后端保持无语言状态，响应也可安全缓存。
 */

export const API_ERROR_CODES = {
  // 通用
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  MISSING_PARAM: 'MISSING_PARAM',
  INVALID_URL: 'INVALID_URL',
  // 认证
  MISSING_PASSWORD: 'MISSING_PASSWORD',
  AUTH_FAILED: 'AUTH_FAILED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  // 云端数据
  MISSING_KEY: 'MISSING_KEY',
  INVALID_KEY: 'INVALID_KEY',
  DATA_PARSE_FAILED: 'DATA_PARSE_FAILED',
  INVALID_JSON: 'INVALID_JSON',
  DATA_TOO_LARGE: 'DATA_TOO_LARGE',
  // 笔记分片
  INVALID_NOTE_ID: 'INVALID_NOTE_ID',
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  CONFIRM_REQUIRED: 'CONFIRM_REQUIRED',
  // 图标
  R2_UNAVAILABLE: 'R2_UNAVAILABLE',
  MISSING_FILE: 'MISSING_FILE',
  ICON_FILE_TOO_LARGE: 'ICON_FILE_TOO_LARGE',
  UNSUPPORTED_FILE_FORMAT: 'UNSUPPORTED_FILE_FORMAT',
  INVALID_DOMAIN: 'INVALID_DOMAIN',
  INVALID_ID: 'INVALID_ID',
  INVALID_HASH_INPUT: 'INVALID_HASH_INPUT',
  MISSING_TARGET_URL: 'MISSING_TARGET_URL',
  ICON_TOO_LARGE: 'ICON_TOO_LARGE',
  ICON_NOT_IMAGE: 'ICON_NOT_IMAGE',
  ICON_DOWNLOAD_FAILED: 'ICON_DOWNLOAD_FAILED',
  ICON_DOWNLOAD_TIMEOUT: 'ICON_DOWNLOAD_TIMEOUT',
  ICON_NETWORK_ERROR: 'ICON_NETWORK_ERROR',
  ALL_SOURCES_FAILED: 'ALL_SOURCES_FAILED',
  ICON_SAVE_FAILED: 'ICON_SAVE_FAILED',
  ICON_DELETE_FAILED: 'ICON_DELETE_FAILED',
  INVALID_ICON_DATA: 'INVALID_ICON_DATA',
  ANALYZE_FAILED: 'ANALYZE_FAILED',
  // 壁纸
  WALLPAPER_FILE_TOO_LARGE: 'WALLPAPER_FILE_TOO_LARGE',
  HTTPS_REQUIRED: 'HTTPS_REQUIRED',
  HOST_NOT_ALLOWED: 'HOST_NOT_ALLOWED',
  WALLPAPER_FETCH_FAILED: 'WALLPAPER_FETCH_FAILED',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  // 天气
  WEATHER_API_NOT_CONFIGURED: 'WEATHER_API_NOT_CONFIGURED',
  INVALID_LOCATION: 'INVALID_LOCATION',
  INVALID_COORDINATES: 'INVALID_COORDINATES',
  GEO_REQUEST_FAILED: 'GEO_REQUEST_FAILED',
  WEATHER_REQUEST_FAILED: 'WEATHER_REQUEST_FAILED',
  // 网站标题
  MISSING_URL: 'MISSING_URL',
  // Bing 壁纸接口
  BING_REQUEST_FAILED: 'BING_REQUEST_FAILED',
  BING_INVALID_RESPONSE: 'BING_INVALID_RESPONSE',
  BING_PROXY_ERROR: 'BING_PROXY_ERROR',
} as const;

export type ApiErrorCode = typeof API_ERROR_CODES[keyof typeof API_ERROR_CODES];

const API_ERROR_CODE_SET: ReadonlySet<string> = new Set(Object.values(API_ERROR_CODES));

export function isApiErrorCode(value: unknown): value is ApiErrorCode {
  return typeof value === 'string' && API_ERROR_CODE_SET.has(value);
}

/** 图标候选来源标识（前端据此展示「HTML / 常见路径 / …」的本地化文案） */
export const ICON_SOURCE_CODES = {
  HTML: 'HTML',
  COMMON_PATH: 'COMMON_PATH',
  SITE_PATH_COMMON_PATH: 'SITE_PATH_COMMON_PATH',
  ICON_SOURCE: 'ICON_SOURCE',
} as const;

export type IconSourceCode = typeof ICON_SOURCE_CODES[keyof typeof ICON_SOURCE_CODES];

const ICON_SOURCE_CODE_SET: ReadonlySet<string> = new Set(Object.values(ICON_SOURCE_CODES));

export function isIconSourceCode(value: unknown): value is IconSourceCode {
  return typeof value === 'string' && ICON_SOURCE_CODE_SET.has(value);
}
